package com.vise.app;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vise.app.GithubModel;
import com.vise.app.Person;

import com.vise.app.GithubModelDao;
import com.vise.app.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig githubModelDaoConfig;
    private final DaoConfig personDaoConfig;

    private final GithubModelDao githubModelDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        githubModelDaoConfig = daoConfigMap.get(GithubModelDao.class).clone();
        githubModelDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        githubModelDao = new GithubModelDao(githubModelDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(GithubModel.class, githubModelDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        githubModelDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public GithubModelDao getGithubModelDao() {
        return githubModelDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
